### PR TITLE
Feat/revamp

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Peek 2024-06-25 13-18

Home page

**Comment by Abdur-rahmaanJ** [comment]
Peek 2024-06-25 13-22

**Comment by Abdur-rahmaanJ** [comment]
Using this as guide: https://www.radix-ui.com/colors for colors

**Comment by mahmoud** [comment]
We appreciate the pop and color @Abdur-rahmaanJ, thank you!

**Review by mahmoud — APPROVED** [review]

**Comment by Abdur-rahmaanJ** [comment]
@mahmoud Thanks, check the about page also ^^

**Comment by mahmoud** [comment]
> @mahmoud Thanks, check the about page also ^^

:100:% community :smile:

**Pull request merged**
